server:
  port: 8081
spring:
  application:
    name: AuroraRemark
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auroraremark?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
    password: redis
    port: 6379
    host: 127.0.0.1

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
#  rabbitmq:
#    virtual-host: /
#    port: 5672
#    username: guest
#    password: guest
#    host: 127.0.0.1
mybatis-plus:
  type-aliases-package: com.qh.entity # 别名扫描包
logging:
  level:
    com.qh.auroraremark: debug